## EdgeX Foundry docker compose file

version: '3'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  newman:

services:
  volume:
    image: ${volume}
    networks:
    - edgex-network
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    - newman:/etc/newman

  consul:
    image: ${consul}
    ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
        - edgex-core-consul
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - volume

  config-seed:
    image: ${configSeed}
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
        - edgex-core-config-seed
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - volume
    - consul

  mongo:
    image: ${mongo}
    ports:
    - "27017:27017"
    hostname: edgex-mongo
    networks:
      edgex-network:
        aliases:
        - edgex-mongo
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    - newman:/etc/newman
    depends_on:
    - volume

  logging:
    image: ${supportLogging}
    ports:
    - "48061:48061"
    hostname: edgex-support-logging
    networks:
      edgex-network:
        aliases:
        - edgex-support-logging
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - config-seed
    - mongo
    - volume

  notifications:
    image: ${supportNotifications}
    ports:
    - "48060:48060"
    hostname: edgex-support-notifications
    networks:
      edgex-network:
        aliases:
        - edgex-support-notifications
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - logging

  metadata:
    image: ${coreMetadata}
    ports:
    - "48081:48081"
    hostname: edgex-core-metadata
    networks:
      edgex-network:
        aliases:
        - edgex-core-metadata
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - logging

  data:
    image: ${coreData}
    ports:
    - "48080:48080"
    - "5563"
    hostname: edgex-core-data
    networks:
      edgex-network:
        aliases:
        - edgex-core-data
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - logging

  command:
    image: ${coreCommand}
    ports:
    - "48082:48082"
    hostname: edgex-core-command
    networks:
      edgex-network:
        aliases:
        - edgex-core-command
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - metadata

  scheduler:
    image: ${supportScheduler}
    ports:
    - "48085:48085"
    hostname: edgex-support-scheduler
    networks:
      edgex-network:
        aliases:
        - edgex-support-scheduler
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - metadata

  export-client:
    image: ${exportClient}
    ports:
    - "48071:48071"
    hostname: edgex-export-client
    networks:
      edgex-network:
        aliases:
        - edgex-export-client
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - data
    environment:
    - EXPORT_CLIENT_MONGO_URL=edgex-mongo
    - EXPORT_CLIENT_DISTRO_HOST=export-distro
    - EXPORT_CLIENT_CONSUL_HOST=edgex-config-seed

  export-distro:
    image: ${exportDistro}
    ports:
    - "48070:48070"
    - "5566"
    hostname: edgex-export-distro
    networks:
      edgex-network:
        aliases:
        - edgex-export-distro
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - export-client
    environment:
    - EXPORT_DISTRO_CLIENT_HOST=export-client
    - EXPORT_DISTRO_DATA_HOST=edgex-core-data
    - EXPORT_DISTRO_CONSUL_HOST=edgex-config-seed
    - EXPORT_DISTRO_MQTTS_CERT_FILE=none
    - EXPORT_DISTRO_MQTTS_KEY_FILE=none

  rulesengine:
    image: ${supportRulesengine}
    ports:
    - "48075:48075"
    hostname: edgex-support-rulesengine
    networks:
      edgex-network:
        aliases:
        - edgex-support-rulesengine
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - export-distro

  #################################################################
  # Device Services
  #################################################################

  device-virtual:
    image: ${deviceVirtual}
    ports:
    - "49990:49990"
    hostname: edgex-device-virtual
    networks:
      edgex-network:
        aliases:
        - edgex-device-virtual
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - data
    - command

  postman:
    image: ${postman}
    networks:
    - edgex-network
    volumes:
    - newman:/etc/newman

    # device-bacnet:
    # image: edgexfoundry/docker-device-bacnet
    # ports:
    # - "49986:49986"
    # container_name: edgex-device-bacnet
    # hostname: edgex-device-bacnet
    # networks:
    # - edgex-network
    # volumes_from:
    # - volume
    # depends_on:
    # - volume
    # - consul
    # - config-seed
    # - mongo
    # - mongo-seed
    # - logging
    # - metadata
    # - data
    # - command

    # device-bluetooth:
    # image: edgexfoundry/docker-device-bluetooth
    # ports:
    # - "49988:49988"
    # container_name: edgex-device-bluetooth
    # hostname: edgex-device-bluetooth
    # networks:
    # - edgex-network
    # volumes_from:
    # - volume
    # privileged: true
    # depends_on:
    # - volume
    # - consul
    # - config-seed
    # - mongo
    # - mongo-seed
    # - logging
    # - metadata
    # - data
    # - command

    # device-fischetechnik:
    # image: edgexfoundry/docker-device-fischetechnik
    # ports:
    # - "49985:49985"
    # container_name: edgex-device-fischetechnik
    # hostname: edgex-device-fischetechnik
    # networks:
    # - edgex-network
    # volumes_from:
    # - volume
    # privileged: true
    # depends_on:
    # - volume
    # - consul
    # - config-seed
    # - mongo
    # - mongo-seed
    # - logging
    # - metadata
    # - data
    # - command

    # device-modbus:
    # image: edgexfoundry/docker-device-modbus
    # ports:
    # - "49991:49991"
    # container_name: edgex-device-modbus
    # hostname: edgex-device-modbus
    # networks:
    # - edgex-network
    # volumes_from:
    # - volume
    # privileged: true
    # depends_on:
    # - volume
    # - consul
    # - config-seed
    # - mongo
    # - mongo-seed
    # - logging
    # - metadata
    # - data
    # - command

    # device-mqtt:
    # image: edgexfoundry/docker-device-mqtt
    # ports:
    # - "49982:49982"
    # container_name: edgex-device-mqtt
    # hostname: edgex-device-mqtt
    # networks:
    # - edgex-network
    # volumes_from:
    # - volume
    # depends_on:
    # - volume
    # - consul
    # - config-seed
    # - mongo
    # - mongo-seed
    # - logging
    # - metadata
    # - data
    # - command

    # device-snmp:
    # image: edgexfoundry/docker-device-snmp
    # ports:
    # - "49989:49989"
    # container_name: edgex-device-snmp
    # hostname: edgex-device-snmp
    # networks:
    # - edgex-network
    # volumes_from:
    # - volume
    # depends_on:
    # - volume
    # - consul
    # - config-seed
    # - mongo
    # - mongo-seed
    # - logging
    # - metadata
    # - data
    # - command

networks:
  edgex-network:
    driver: "bridge"
